src/Controllers/RootController.cs
using System;
using System.Text;
using IOL.VippsEcommerce;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using VSH.Data.Static;

namespace VSH.Controllers;

public class RootController : MainControllerBase
{
	private readonly IVippsEcommerceService _vippsEcommerceService;
	private readonly IConfiguration _configuration;

	public RootController(IConfiguration configuration, IVippsEcommerceService vippsEcommerceService) {
		_configuration = configuration;
		_vippsEcommerceService = vippsEcommerceService;
	}

	[HttpGet("~/kontoret")]
	public ActionResult AdminRedirect() {
		return Redirect("/kontoret/produkter");
	}

	[Authorize]
	[HttpGet("~/info")]
	public ActionResult GetInfo() {
		var infoString = new StringBuilder();
		infoString.AppendLine("Variables");
		infoString.AppendLine($" - CurrentHost: {CurrentHost}");
		infoString.AppendLine("Environment");
		infoString.AppendLine($" - DB_HOST: {_configuration.GetValue("DB_HOST", "unset")}");
		infoString.AppendLine($" - DB_PORT: {_configuration.GetValue("DB_PORT", "unset")}");
		infoString.AppendLine($" - DB_USER: {_configuration.GetValue("DB_USER", "unset")}");
		infoString.AppendLine($" - DB_PASSWORD: {HiddenIfSet(_configuration.GetValue("DB_PASSWORD", "unset"))}");
		infoString.AppendLine($" - DB_NAME: {_configuration.GetValue("DB_NAME", "unset")}");
		infoString.AppendLine($" - SENDGRID_API_KEY: {HiddenIfSet(_configuration.GetValue("SENDGRID_API_KEY", "unset"))}");
		infoString.AppendLine($" - MAIL_FROM_ADDRESS: {_configuration.GetValue("MAIL_FROM_ADDRESS", "unset")}");
		infoString.AppendLine($" - MAIL_REPLY_TO_ADDRESS: {_configuration.GetValue("MAIL_REPLY_TO_ADDRESS", "unset")}");
		infoString.AppendLine($" - MAIL_FROM_NAME: {_configuration.GetValue("MAIL_FROM_NAME", "unset")}");
		infoString.AppendLine("Headers");
		infoString.AppendLine($" - X-Forwarded-For: {Request.Headers["X-Forwarded-For"]}");
		infoString.AppendLine($" - X-Real-IP: {Request.Headers["X-Real-IP"]}");
		infoString.AppendLine($" - X-Forwarded-Host: {Request.Headers["X-Forwarded-Host"]}");
		infoString.AppendLine($" - X-Forwarded-Proto: {Request.Headers["X-Forwarded-Proto"]}");
		return Ok(infoString.ToString());
	}

	[Authorize]
	[HttpGet("~/vipps-config")]
	public ActionResult GetVippsConfiguration() {
		return Ok(_vippsEcommerceService.Configuration);
	}

	private string HiddenIfSet(string value) {
		return value == "unset" ? "unset" : "*****";
	}

	[HttpPost("~/set-culture")]
	public ActionResult SetCulture(
			[FromForm] string culture,
			[FromQuery] string returnUrl
	) {
		Response.Cookies.Append(AppCookies.Culture.Name,
								CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
								new CookieOptions {
										Expires = DateTimeOffset.UtcNow.AddYears(1)
								});

		return LocalRedirect(returnUrl);
	}
}

src/Pages/Partials/_AdminCategoriesModal.cshtml
<div class="modal" tabindex="-1" id="categories-modal">
    <div class="modal-dialog modal-dialog-scrollable modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Kategorier</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="card">
                    <div class="card-header p-3">
                        <form onsubmit="return false;" id="new-category-form">
                            <input type="text" class="form-control" id="new-category-name" name="new-category-name" placeholder="Legg til en ny kategori" autocomplete="off" required>
                        </form>
                    </div>
                    <div class="d-flex justify-content-center p-3" id="loading-wrapper">
                        <div class="spinner-border" role="status">
                            <span class="visually-hidden">Laster...</span>
                        </div>
                    </div>
                    <div class="list-group list-group-flush d-none" id="list-wrapper"></div>
                </div>
            </div>
        </div>
    </div>
</div>

src/Pages/Partials/_AdminProductModal.cshtml
<div class="modal" tabindex="-1" id="product-modal">
    <div class="modal-dialog modal-dialog-scrollable modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="product-modal-title">Nytt produkt</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form class="margin-bottom-sm" id="product-form">
                    <div class="loader">
                        <div class="spinner-border" role="status">
                            <span class="visually-hidden">Laster...</span>
                        </div>
                    </div>
                    <fieldset class="mb-3">
                        <label class="form-label mb-2" for="input-name">Navn</label>
                        <input class="form-control" type="text" name="input-name" id="input-name" required/>
                    </fieldset>
                    <fieldset class="mb-3 row">
                        <div class="col">
                            <label class="form-label mb-2" for="input-price">Pris</label>
                            <div class="input-group">
                                <input class="form-control" type="text" name="input-price" id="input-price" required/>
                                <select class="form-select" style="max-width: 85px;" id="input-price-suffix">
                                    <option selected value="0">,-</option>
                                    <option value="1">,- kg</option>
                                </select>
                            </div>
                        </div>
                        <div class="col">
                            <label class="form-label mb-2" for="input-count">Besetning (-1 for uendelig)</label>
                            <div class="input-group">
                                <input class="form-control" type="number" min="-1" name="input-count" id="input-count" placeholder="Antall produkter/kilo for salg"/>
                            </div>
                        </div>
                    </fieldset>
                    <fieldset class="mb-3">
                        <label class="form-label mb-2" for="input-description">Beskrivelse</label>
                        <textarea class="form-control" name="input-description" id="input-description"></textarea>
                    </fieldset>
                    <fieldset class="mb-3">
                        <label for="" class="form-label mb-2">Bilder</label>
                        <div class="row pb-2" id="input-images-row">
                        </div>
                    </fieldset>
                    <fieldset class="form-check form-switch mb-3">
                        <input class="form-check-input" type="checkbox" id="show-on-frontpage" name="show-on-frontpage">
                        <label class="form-check-label" for="show-on-frontpage">Vis på forsiden</label>
                    </fieldset>
                    <fieldset class="mb-3">
                        <label for="" class="form-label mb-2">Kategori</label>
                        <div id="product-category-picker-wrapper">
                            <div id="picker" class="d-none"></div>
                            <div class="d-flex justify-content-center" id="loader">
                                <div class="spinner-border" role="status">
                                    <span class="visually-hidden">Laster...</span>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-lg btn-secondary" data-bs-dismiss="modal">Avbryt</button>
                <button type="button" class="btn btn-lg btn-primary" id="submit-product-form">
                    <span class="spinner-border spinner-border-sm d-none" role="status" aria-hidden="true"></span>
                    <span class="text">Lagre</span>
                </button>
            </div>
        </div>
    </div>
</div>

src/Pages/Partials/_CultureSelector.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Localization
@using Microsoft.Extensions.Options
@using IOL.Helpers

@inject IStringLocalizer<SharedPageResources> Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures;
}

<div>
    <form asp-controller="Root"
          asp-action="SetCulture"
          asp-route-returnUrl="@Context.Request.Path"
          method="post"
          class="row row-cols-lg-auto g-3 align-items-center"
          role="form">
        <div class="col">
            <select class="form-control" name="culture">
                @foreach (var item in cultureItems) {
                    if (item.Name == requestCulture?.RequestCulture.UICulture.Name) {
                        <option value="@item.Name" selected>@item.NativeName.Capitalize()</option>
                    } else {
                        <option value="@item.Name">@item.NativeName.Capitalize()</option>
                    }
                }
            </select>
        </div>
        <button type="submit" class="btn btn-default btn-xs">@Localizer["Lagre"]</button>
    </form>
</div>